name: Release docker images
on:
  push:
    branches: [release-staging, release-prod]

jobs:
  release-staging:
    runs-on: self-hosted
    env:
      USERNAME: ${{ secrets.GH_USERNAME }}
      ACCESS_TOKEN: ${{secrets.GH_TOKEN}}
    timeout-minutes: 10
    if: github.ref == 'refs/heads/release-staging'
    steps:
      - name: Checkout injective-guilds-service
        uses: actions/checkout@master
        with:
          repository: InjectiveLabs/injective-guilds-service
          ref: release-staging
          token: ${{ secrets.GH_TOKEN }}
          path: ./injective-guilds-service
      - name: Build image
        run: |
          cd injective-guilds-service
          go env -w GOPRIVATE=github.com/InjectiveLabs/*
          git config --global url."https://$USERNAME:$ACCESS_TOKEN@github.com".insteadOf "https://github.com"
          go mod tidy
          docker build -t public.ecr.aws/l9h3g6c6/injective-guilds-service:staging .
      - name: Push image
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET }}
          aws configure set region us-east-1
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l9h3g6c6
          docker push public.ecr.aws/l9h3g6c6/injective-guilds-service:staging

  release-prod:
    runs-on: self-hosted
    env:
      USERNAME: ${{ secrets.GH_USERNAME }}
      ACCESS_TOKEN: ${{secrets.GH_TOKEN}}
    timeout-minutes: 10
    if: github.ref == 'refs/heads/release-prod'
    steps:
      - name: Checkout injective-guilds-service
        uses: actions/checkout@master
        with:
          repository: InjectiveLabs/injective-guilds-service
          ref: release-prod
          token: ${{ secrets.GH_TOKEN }}
          path: ./injective-guilds-service
      - name: Build image
        run: |
          cd injective-guilds-service
          go env -w GOPRIVATE=github.com/InjectiveLabs/*
          git config --global url."https://$USERNAME:$ACCESS_TOKEN@github.com".insteadOf "https://github.com"
          go mod tidy
          docker build -t public.ecr.aws/l9h3g6c6/injective-guilds-service:prod .
      - name: Push image
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET }}
          aws configure set region us-east-1
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l9h3g6c6
          docker push public.ecr.aws/l9h3g6c6/injective-guilds-service:prod